FROM python:3.8
COPY ./app.py /vk_api/app.py
COPY ./requirements.txt /vk_api/requirements.txt
WORKDIR /vk_api
RUN pip install -r requirements.txt
EXPOSE 5000
CMD python -m flask run --port 5000 --host 0.0.0.0
